version: "3.7"
services:
  app_l7:
    build:
      args:
        user: davi
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db_l7
    volumes:
      - ./:/var/www
    networks:
      - lahmi
      
  db_l7:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: local_laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: local_developer
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - lahmi

  phpmyadmin_l7:
    image: phpmyadmin/phpmyadmin
    links:
      - db_l7
    environment:
      PMA_HOST: db_l7
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - lahmi

  nginx_l7:
    image: nginx:alpine
    ports:
      - 8005:80
    depends_on:
      - db_l7
      - app_l7
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lahmi

networks:
  lahmi:
    driver: bridge

volumes:
  dbdata:
    driver: local
